// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"my-gift/configs"
	"my-gift/internal/infra"
	"my-gift/internal/sample"
)

import (
	_ "my-gift/docs"
)

// Injectors from wire.go:

// InitializeApp wires the full app with PostgreSQL.
func InitializeApp(cfg *configs.Config) (*App, error) {
	logger, err := infra.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	db, err := infra.NewDatabase(cfg, logger)
	if err != nil {
		return nil, err
	}
	sampleRepository := sample.ProvideRepository(db)
	sampleService := sample.ProvideService(sampleRepository)
	controller := sample.ProvideController(sampleService)
	grpcHandler := sample.ProvideGRPCHandler(sampleService)
	app := NewApp(cfg, logger, controller, grpcHandler)
	return app, nil
}

// InitializeAppDummy wires the app with an in-memory repository (no DB).
func InitializeAppDummy(cfg *configs.Config) (*App, error) {
	logger, err := infra.NewLogger(cfg)
	if err != nil {
		return nil, err
	}
	sampleRepository := sample.NewSampleRepositoryDummy()
	sampleService := sample.ProvideService(sampleRepository)
	controller := sample.ProvideController(sampleService)
	grpcHandler := sample.ProvideGRPCHandler(sampleService)
	app := NewApp(cfg, logger, controller, grpcHandler)
	return app, nil
}

// wire.go:

var infraSet = wire.NewSet(infra.NewLogger, infra.NewDatabase)

var loggerSet = wire.NewSet(infra.NewLogger)

var sampleSet = wire.NewSet(sample.ProvideRepository, sample.ProvideService, sample.ProvideController, sample.ProvideGRPCHandler)

var dummySampleSet = wire.NewSet(sample.NewSampleRepositoryDummy, sample.ProvideService, sample.ProvideController, sample.ProvideGRPCHandler)
